name: Build and deploy full-stack app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install and build the client
      - name: Install and build client
        run: |
          cd client
          npm ci
          npm run build --if-present

      # Install server dependencies
      - name: Install server dependencies
        run: npm ci
      
      # Zip both client and server code
      - name: Zip the full build
        run: zip -r full-build.zip client/build . -x "node_modules/\*"

      # Upload the zipped artifact
      - name: Upload zipped artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: full-build-artifact
          path: full-build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download zipped artifact from build job
      - name: Download zipped artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: full-build-artifact

      # Unzip the build artifact
      - name: Unzip the build artifact
        run: unzip full-build.zip -d ./unzipped-build

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Swaps'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6793DE84C4C54BF291358D26ED28C933 }}
          package: ./unzipped-build/
